### ISSUE TITLE
Keyboard Navigation

### ISSUE THREAD

**Issue by njrey** [pinkhominid/navmore#1]
Hey, it's Nolan from TR! Hope you've been doing well!
  
We've been asked to add keyboard navigation to our nav to meet some a11y requirements coming up in UK. I'd like to keep using navmore for now, so our package consumers there can get the keyboard navigation without making changes on their end.
  
I was thinking I'd do some work on it this week and then make a pull request here. Please let me know if you have any input!

**Comment by pinkhominid** [comment]
Hey Nolan! Sounds good. This is an important and needed improvement.

**Comment by pinkhominid** [comment]
Is there any way I can help here? What are the major sticking points that you are wanting to address?

**Comment by njrey** [comment]
I'm actually working on a change now, but I'm hoping to have it up today or tomorrow if you don't mind taking a look then.
   
We want users to be able to tab through the nav and interact with the "enter" key. I'm thinking we can just add top-level nav items to the tabindex, and handle the "enter" keypress with the existing handleTap function. 
  
Right now, I'm working on setting it up so nested list items (dropdown items) aren't tab-able until the user has opened that dropdown menu.
   
I'll be on slack today if you have any feedback on that approach!

**Comment by pinkhominid** [comment]
Hey Nolan. Thanks for the PR. I had a few thoughts, but didn't get a chance to share them. Been a busy day. I'll have a look at the PR as soon as I can.

**Comment by pinkhominid** [comment]
Released in 3.0.0
